// Country, State/Province, and Local Jurisdiction data for dropdowns

export const countries = [
  { value: "nepal", label: "Nepal" },
  { value: "india", label: "India" },
  { value: "usa", label: "United States" },
  { value: "uk", label: "United Kingdom" },
  { value: "australia", label: "Australia" },
  { value: "canada", label: "Canada" },
  { value: "germany", label: "Germany" },
  { value: "france", label: "France" },
  { value: "japan", label: "Japan" },
  { value: "china", label: "China" },
  { value: "bangladesh", label: "Bangladesh" },
  { value: "pakistan", label: "Pakistan" },
  { value: "bhutan", label: "Bhutan" },
  { value: "myanmar", label: "Myanmar" },
  { value: "sri_lanka", label: "Sri Lanka" },
  { value: "other", label: "Other" }
];

// States/Provinces by country
export const statesByCountry: Record<string, Array<{ value: string, label: string }>> = {
  nepal: [
    { value: "province_1", label: "Province 1" },
    { value: "madhesh", label: "Madhesh Province" },
    { value: "bagmati", label: "Bagmati Province" },
    { value: "gandaki", label: "Gandaki Province" },
    { value: "lumbini", label: "Lumbini Province" },
    { value: "karnali", label: "Karnali Province" },
    { value: "sudurpashchim", label: "Sudurpashchim Province" },
  ],
  india: [
    { value: "andhra_pradesh", label: "Andhra Pradesh" },
    { value: "arunachal_pradesh", label: "Arunachal Pradesh" },
    { value: "assam", label: "Assam" },
    { value: "bihar", label: "Bihar" },
    { value: "chhattisgarh", label: "Chhattisgarh" },
    { value: "goa", label: "Goa" },
    { value: "gujarat", label: "Gujarat" },
    { value: "haryana", label: "Haryana" },
    { value: "himachal_pradesh", label: "Himachal Pradesh" },
    { value: "jharkhand", label: "Jharkhand" },
    { value: "karnataka", label: "Karnataka" },
    { value: "kerala", label: "Kerala" },
    { value: "madhya_pradesh", label: "Madhya Pradesh" },
    { value: "maharashtra", label: "Maharashtra" },
    { value: "manipur", label: "Manipur" },
    { value: "meghalaya", label: "Meghalaya" },
    { value: "mizoram", label: "Mizoram" },
    { value: "nagaland", label: "Nagaland" },
    { value: "odisha", label: "Odisha" },
    { value: "punjab", label: "Punjab" },
    { value: "rajasthan", label: "Rajasthan" },
    { value: "sikkim", label: "Sikkim" },
    { value: "tamil_nadu", label: "Tamil Nadu" },
    { value: "telangana", label: "Telangana" },
    { value: "tripura", label: "Tripura" },
    { value: "uttar_pradesh", label: "Uttar Pradesh" },
    { value: "uttarakhand", label: "Uttarakhand" },
    { value: "west_bengal", label: "West Bengal" },
    { value: "delhi", label: "Delhi" },
  ],
  usa: [
    { value: "alabama", label: "Alabama" },
    { value: "alaska", label: "Alaska" },
    { value: "arizona", label: "Arizona" },
    { value: "arkansas", label: "Arkansas" },
    { value: "california", label: "California" },
    { value: "colorado", label: "Colorado" },
    { value: "connecticut", label: "Connecticut" },
    { value: "delaware", label: "Delaware" },
    { value: "florida", label: "Florida" },
    { value: "georgia", label: "Georgia" },
    { value: "hawaii", label: "Hawaii" },
    { value: "idaho", label: "Idaho" },
    { value: "illinois", label: "Illinois" },
    { value: "indiana", label: "Indiana" },
    { value: "iowa", label: "Iowa" },
    { value: "kansas", label: "Kansas" },
    { value: "kentucky", label: "Kentucky" },
    { value: "louisiana", label: "Louisiana" },
    { value: "maine", label: "Maine" },
    { value: "maryland", label: "Maryland" },
    { value: "massachusetts", label: "Massachusetts" },
    { value: "michigan", label: "Michigan" },
    { value: "minnesota", label: "Minnesota" },
    { value: "mississippi", label: "Mississippi" },
    { value: "missouri", label: "Missouri" },
    { value: "montana", label: "Montana" },
    { value: "nebraska", label: "Nebraska" },
    { value: "nevada", label: "Nevada" },
    { value: "new_hampshire", label: "New Hampshire" },
    { value: "new_jersey", label: "New Jersey" },
    { value: "new_mexico", label: "New Mexico" },
    { value: "new_york", label: "New York" },
    { value: "north_carolina", label: "North Carolina" },
    { value: "north_dakota", label: "North Dakota" },
    { value: "ohio", label: "Ohio" },
    { value: "oklahoma", label: "Oklahoma" },
    { value: "oregon", label: "Oregon" },
    { value: "pennsylvania", label: "Pennsylvania" },
    { value: "rhode_island", label: "Rhode Island" },
    { value: "south_carolina", label: "South Carolina" },
    { value: "south_dakota", label: "South Dakota" },
    { value: "tennessee", label: "Tennessee" },
    { value: "texas", label: "Texas" },
    { value: "utah", label: "Utah" },
    { value: "vermont", label: "Vermont" },
    { value: "virginia", label: "Virginia" },
    { value: "washington", label: "Washington" },
    { value: "west_virginia", label: "West Virginia" },
    { value: "wisconsin", label: "Wisconsin" },
    { value: "wyoming", label: "Wyoming" },
  ]
};

// Districts by province for Nepal
export const districtsByProvince: Record<string, Array<{ value: string, label: string }>> = {
  province_1: [
    { value: "taplejung", label: "Taplejung" },
    { value: "sankhuwasabha", label: "Sankhuwasabha" },
    { value: "solukhumbu", label: "Solukhumbu" },
    { value: "okhaldhunga", label: "Okhaldhunga" },
    { value: "khotang", label: "Khotang" },
    { value: "bhojpur", label: "Bhojpur" },
    { value: "dhankuta", label: "Dhankuta" },
    { value: "terhathum", label: "Terhathum" },
    { value: "panchthar", label: "Panchthar" },
    { value: "ilam", label: "Ilam" },
    { value: "jhapa", label: "Jhapa" },
    { value: "morang", label: "Morang" },
    { value: "sunsari", label: "Sunsari" },
    { value: "udayapur", label: "Udayapur" },
  ],
  madhesh: [
    { value: "saptari", label: "Saptari" },
    { value: "siraha", label: "Siraha" },
    { value: "dhanusa", label: "Dhanusa" },
    { value: "mahottari", label: "Mahottari" },
    { value: "sarlahi", label: "Sarlahi" },
    { value: "rautahat", label: "Rautahat" },
    { value: "bara", label: "Bara" },
    { value: "parsa", label: "Parsa" },
  ],
  bagmati: [
    { value: "dolakha", label: "Dolakha" },
    { value: "sindhupalchok", label: "Sindhupalchok" },
    { value: "rasuwa", label: "Rasuwa" },
    { value: "dhading", label: "Dhading" },
    { value: "nuwakot", label: "Nuwakot" },
    { value: "kathmandu", label: "Kathmandu" },
    { value: "bhaktapur", label: "Bhaktapur" },
    { value: "lalitpur", label: "Lalitpur" },
    { value: "kavrepalanchok", label: "Kavrepalanchok" },
    { value: "ramechhap", label: "Ramechhap" },
    { value: "sindhuli", label: "Sindhuli" },
    { value: "makawanpur", label: "Makawanpur" },
    { value: "chitwan", label: "Chitwan" },
  ],
  gandaki: [
    { value: "gorkha", label: "Gorkha" },
    { value: "manang", label: "Manang" },
    { value: "mustang", label: "Mustang" },
    { value: "myagdi", label: "Myagdi" },
    { value: "kaski", label: "Kaski" },
    { value: "lamjung", label: "Lamjung" },
    { value: "tanahu", label: "Tanahu" },
    { value: "nawalparasi_east", label: "Nawalparasi East" },
    { value: "syangja", label: "Syangja" },
    { value: "parbat", label: "Parbat" },
    { value: "baglung", label: "Baglung" },
  ],
  lumbini: [
    { value: "rukum_east", label: "Rukum East" },
    { value: "rolpa", label: "Rolpa" },
    { value: "pyuthan", label: "Pyuthan" },
    { value: "gulmi", label: "Gulmi" },
    { value: "arghakhanchi", label: "Arghakhanchi" },
    { value: "palpa", label: "Palpa" },
    { value: "nawalparasi_west", label: "Nawalparasi West" },
    { value: "rupandehi", label: "Rupandehi" },
    { value: "kapilvastu", label: "Kapilvastu" },
    { value: "dang", label: "Dang" },
    { value: "banke", label: "Banke" },
    { value: "bardiya", label: "Bardiya" },
  ],
  karnali: [
    { value: "dolpa", label: "Dolpa" },
    { value: "mugu", label: "Mugu" },
    { value: "humla", label: "Humla" },
    { value: "jumla", label: "Jumla" },
    { value: "kalikot", label: "Kalikot" },
    { value: "dailekh", label: "Dailekh" },
    { value: "jajarkot", label: "Jajarkot" },
    { value: "rukum_west", label: "Rukum West" },
    { value: "salyan", label: "Salyan" },
    { value: "surkhet", label: "Surkhet" },
  ],
  sudurpashchim: [
    { value: "bajura", label: "Bajura" },
    { value: "bajhang", label: "Bajhang" },
    { value: "darchula", label: "Darchula" },
    { value: "baitadi", label: "Baitadi" },
    { value: "dadeldhura", label: "Dadeldhura" },
    { value: "kanchanpur", label: "Kanchanpur" },
    { value: "kailali", label: "Kailali" },
    { value: "doti", label: "Doti" },
    { value: "achham", label: "Achham" },
  ],
};

// Local jurisdictions by district in Nepal (adding just a few examples)
export const localJurisdictionsByDistrict: Record<string, Array<{ value: string, label: string }>> = {
  kathmandu: [
    { value: "kathmandu_metropolitan", label: "Kathmandu Metropolitan City" },
    { value: "kirtipur", label: "Kirtipur Municipality" },
    { value: "chandragiri", label: "Chandragiri Municipality" },
    { value: "kageshwori_manohara", label: "Kageshwori Manohara Municipality" },
    { value: "tarakeshwar", label: "Tarakeshwar Municipality" },
    { value: "dakshinkali", label: "Dakshinkali Municipality" },
    { value: "nagarjun", label: "Nagarjun Municipality" },
    { value: "budhanilkantha", label: "Budhanilkantha Municipality" },
    { value: "tokha", label: "Tokha Municipality" },
    { value: "gokarneshwar", label: "Gokarneshwar Municipality" },
    { value: "shankarapur", label: "Shankarapur Municipality" },
  ],
  lalitpur: [
    { value: "lalitpur_metropolitan", label: "Lalitpur Metropolitan City" },
    { value: "mahalaxmi", label: "Mahalaxmi Municipality" },
    { value: "godawari", label: "Godawari Municipality" },
    { value: "konjyosom", label: "Konjyosom Rural Municipality" },
    { value: "bagmati", label: "Bagmati Rural Municipality" },
    { value: "mahankal", label: "Mahankal Rural Municipality" },
  ],
  bhaktapur: [
    { value: "bhaktapur", label: "Bhaktapur Municipality" },
    { value: "madhyapur_thimi", label: "Madhyapur Thimi Municipality" },
    { value: "suryabinayak", label: "Suryabinayak Municipality" },
    { value: "changunarayan", label: "Changunarayan Municipality" },
  ],
  chitwan: [
    { value: "bharatpur", label: "Bharatpur Metropolitan City" },
    { value: "kalika", label: "Kalika Municipality" },
    { value: "khairahani", label: "Khairahani Municipality" },
    { value: "madi", label: "Madi Municipality" },
    { value: "ratnanagar", label: "Ratnanagar Municipality" },
    { value: "rapti", label: "Rapti Municipality" },
    { value: "ichchhakamana", label: "Ichchhakamana Rural Municipality" },
  ],
};

export const getStateOptions = (country: string) => {
  return statesByCountry[country] || [];
};

export const getDistrictOptions = (province: string) => {
  return districtsByProvince[province] || [];
};

export const getLocalJurisdictionOptions = (district: string) => {
  return localJurisdictionsByDistrict[district] || [];
};
