// Country, State/Province, and Local Jurisdiction data for dropdowns

export const countries = [
  { value: "nepal", label: "Nepal" },
  { value: "india", label: "India" },
  { value: "usa", label: "United States" },
  { value: "uk", label: "United Kingdom" },
  { value: "australia", label: "Australia" },
  { value: "canada", label: "Canada" },
  { value: "germany", label: "Germany" },
  { value: "france", label: "France" },
  { value: "japan", label: "Japan" },
  { value: "china", label: "China" },
  { value: "bangladesh", label: "Bangladesh" },
  { value: "pakistan", label: "Pakistan" },
  { value: "bhutan", label: "Bhutan" },
  { value: "myanmar", label: "Myanmar" },
  { value: "sri_lanka", label: "Sri Lanka" },
  { value: "other", label: "Other" }
];

// States/Provinces by country
export const statesByCountry: Record<string, Array<{ value: string, label: string }>> = {
  nepal: [
    { value: "province_1", label: "Province 1" },
    { value: "madhesh", label: "Madhesh Province" },
    { value: "bagmati", label: "Bagmati Province" },
    { value: "gandaki", label: "Gandaki Province" },
    { value: "lumbini", label: "Lumbini Province" },
    { value: "karnali", label: "Karnali Province" },
    { value: "sudurpashchim", label: "Sudurpashchim Province" },
  ],
  india: [
    { value: "andhra_pradesh", label: "Andhra Pradesh" },
    { value: "arunachal_pradesh", label: "Arunachal Pradesh" },
    { value: "assam", label: "Assam" },
    { value: "bihar", label: "Bihar" },
    { value: "chhattisgarh", label: "Chhattisgarh" },
    { value: "goa", label: "Goa" },
    { value: "gujarat", label: "Gujarat" },
    { value: "haryana", label: "Haryana" },
    { value: "himachal_pradesh", label: "Himachal Pradesh" },
    { value: "jharkhand", label: "Jharkhand" },
    { value: "karnataka", label: "Karnataka" },
    { value: "kerala", label: "Kerala" },
    { value: "madhya_pradesh", label: "Madhya Pradesh" },
    { value: "maharashtra", label: "Maharashtra" },
    { value: "manipur", label: "Manipur" },
    { value: "meghalaya", label: "Meghalaya" },
    { value: "mizoram", label: "Mizoram" },
    { value: "nagaland", label: "Nagaland" },
    { value: "odisha", label: "Odisha" },
    { value: "punjab", label: "Punjab" },
    { value: "rajasthan", label: "Rajasthan" },
    { value: "sikkim", label: "Sikkim" },
    { value: "tamil_nadu", label: "Tamil Nadu" },
    { value: "telangana", label: "Telangana" },
    { value: "tripura", label: "Tripura" },
    { value: "uttar_pradesh", label: "Uttar Pradesh" },
    { value: "uttarakhand", label: "Uttarakhand" },
    { value: "west_bengal", label: "West Bengal" },
    { value: "delhi", label: "Delhi" },
  ],
  usa: [
    { value: "alabama", label: "Alabama" },
    { value: "alaska", label: "Alaska" },
    { value: "arizona", label: "Arizona" },
    { value: "arkansas", label: "Arkansas" },
    { value: "california", label: "California" },
    { value: "colorado", label: "Colorado" },
    { value: "connecticut", label: "Connecticut" },
    { value: "delaware", label: "Delaware" },
    { value: "florida", label: "Florida" },
    { value: "georgia", label: "Georgia" },
    { value: "hawaii", label: "Hawaii" },
    { value: "idaho", label: "Idaho" },
    { value: "illinois", label: "Illinois" },
    { value: "indiana", label: "Indiana" },
    { value: "iowa", label: "Iowa" },
    { value: "kansas", label: "Kansas" },
    { value: "kentucky", label: "Kentucky" },
    { value: "louisiana", label: "Louisiana" },
    { value: "maine", label: "Maine" },
    { value: "maryland", label: "Maryland" },
    { value: "massachusetts", label: "Massachusetts" },
    { value: "michigan", label: "Michigan" },
    { value: "minnesota", label: "Minnesota" },
    { value: "mississippi", label: "Mississippi" },
    { value: "missouri", label: "Missouri" },
    { value: "montana", label: "Montana" },
    { value: "nebraska", label: "Nebraska" },
    { value: "nevada", label: "Nevada" },
    { value: "new_hampshire", label: "New Hampshire" },
    { value: "new_jersey", label: "New Jersey" },
    { value: "new_mexico", label: "New Mexico" },
    { value: "new_york", label: "New York" },
    { value: "north_carolina", label: "North Carolina" },
    { value: "north_dakota", label: "North Dakota" },
    { value: "ohio", label: "Ohio" },
    { value: "oklahoma", label: "Oklahoma" },
    { value: "oregon", label: "Oregon" },
    { value: "pennsylvania", label: "Pennsylvania" },
    { value: "rhode_island", label: "Rhode Island" },
    { value: "south_carolina", label: "South Carolina" },
    { value: "south_dakota", label: "South Dakota" },
    { value: "tennessee", label: "Tennessee" },
    { value: "texas", label: "Texas" },
    { value: "utah", label: "Utah" },
    { value: "vermont", label: "Vermont" },
    { value: "virginia", label: "Virginia" },
    { value: "washington", label: "Washington" },
    { value: "west_virginia", label: "West Virginia" },
    { value: "wisconsin", label: "Wisconsin" },
    { value: "wyoming", label: "Wyoming" },
  ]
};

// Districts by province for Nepal
export const districtsByProvince: Record<string, Array<{ value: string, label: string }>> = {
  province_1: [
    { value: "taplejung", label: "Taplejung" },
    { value: "sankhuwasabha", label: "Sankhuwasabha" },
    { value: "solukhumbu", label: "Solukhumbu" },
    { value: "okhaldhunga", label: "Okhaldhunga" },
    { value: "khotang", label: "Khotang" },
    { value: "bhojpur", label: "Bhojpur" },
    { value: "dhankuta", label: "Dhankuta" },
    { value: "terhathum", label: "Terhathum" },
    { value: "panchthar", label: "Panchthar" },
    { value: "ilam", label: "Ilam" },
    { value: "jhapa", label: "Jhapa" },
    { value: "morang", label: "Morang" },
    { value: "sunsari", label: "Sunsari" },
    { value: "udayapur", label: "Udayapur" },
  ],
  madhesh: [
    { value: "saptari", label: "Saptari" },
    { value: "siraha", label: "Siraha" },
    { value: "dhanusa", label: "Dhanusa" },
    { value: "mahottari", label: "Mahottari" },
    { value: "sarlahi", label: "Sarlahi" },
    { value: "rautahat", label: "Rautahat" },
    { value: "bara", label: "Bara" },
    { value: "parsa", label: "Parsa" },
  ],
  bagmati: [
    { value: "dolakha", label: "Dolakha" },
    { value: "sindhupalchok", label: "Sindhupalchok" },
    { value: "rasuwa", label: "Rasuwa" },
    { value: "dhading", label: "Dhading" },
    { value: "nuwakot", label: "Nuwakot" },
    { value: "kathmandu", label: "Kathmandu" },
    { value: "bhaktapur", label: "Bhaktapur" },
    { value: "lalitpur", label: "Lalitpur" },
    { value: "kavrepalanchok", label: "Kavrepalanchok" },
    { value: "ramechhap", label: "Ramechhap" },
    { value: "sindhuli", label: "Sindhuli" },
    { value: "makawanpur", label: "Makawanpur" },
    { value: "chitwan", label: "Chitwan" },
  ],
  gandaki: [
    { value: "gorkha", label: "Gorkha" },
    { value: "manang", label: "Manang" },
    { value: "mustang", label: "Mustang" },
    { value: "myagdi", label: "Myagdi" },
    { value: "kaski", label: "Kaski" },
    { value: "lamjung", label: "Lamjung" },
    { value: "tanahu", label: "Tanahu" },
    { value: "nawalparasi_east", label: "Nawalparasi East" },
    { value: "syangja", label: "Syangja" },
    { value: "parbat", label: "Parbat" },
    { value: "baglung", label: "Baglung" },
  ],
  lumbini: [
    { value: "rukum_east", label: "Rukum East" },
    { value: "rolpa", label: "Rolpa" },
    { value: "pyuthan", label: "Pyuthan" },
    { value: "gulmi", label: "Gulmi" },
    { value: "arghakhanchi", label: "Arghakhanchi" },
    { value: "palpa", label: "Palpa" },
    { value: "nawalparasi_west", label: "Nawalparasi West" },
    { value: "rupandehi", label: "Rupandehi" },
    { value: "kapilvastu", label: "Kapilvastu" },
    { value: "dang", label: "Dang" },
    { value: "banke", label: "Banke" },
    { value: "bardiya", label: "Bardiya" },
  ],
  karnali: [
    { value: "dolpa", label: "Dolpa" },
    { value: "mugu", label: "Mugu" },
    { value: "humla", label: "Humla" },
    { value: "jumla", label: "Jumla" },
    { value: "kalikot", label: "Kalikot" },
    { value: "dailekh", label: "Dailekh" },
    { value: "jajarkot", label: "Jajarkot" },
    { value: "rukum_west", label: "Rukum West" },
    { value: "salyan", label: "Salyan" },
    { value: "surkhet", label: "Surkhet" },
  ],
  sudurpashchim: [
    { value: "bajura", label: "Bajura" },
    { value: "bajhang", label: "Bajhang" },
    { value: "darchula", label: "Darchula" },
    { value: "baitadi", label: "Baitadi" },
    { value: "dadeldhura", label: "Dadeldhura" },
    { value: "kanchanpur", label: "Kanchanpur" },
    { value: "kailali", label: "Kailali" },
    { value: "doti", label: "Doti" },
    { value: "achham", label: "Achham" },
  ],
};

// Local jurisdictions by district in Nepal (adding just a few examples)
export const localJurisdictionsByDistrict: Record<string, Array<{ value: string, label: string }>> = {
  kathmandu: [
    { value: "kathmandu_metropolitan", label: "Kathmandu Metropolitan City" },
    { value: "kirtipur", label: "Kirtipur Municipality" },
    { value: "chandragiri", label: "Chandragiri Municipality" },
    { value: "kageshwori_manohara", label: "Kageshwori Manohara Municipality" },
    { value: "tarakeshwar", label: "Tarakeshwar Municipality" },
    { value: "dakshinkali", label: "Dakshinkali Municipality" },
    { value: "nagarjun", label: "Nagarjun Municipality" },
    { value: "budhanilkantha", label: "Budhanilkantha Municipality" },
    { value: "tokha", label: "Tokha Municipality" },
    { value: "gokarneshwar", label: "Gokarneshwar Municipality" },
    { value: "shankarapur", label: "Shankarapur Municipality" },
  ],
  lalitpur: [
    { value: "lalitpur_metropolitan", label: "Lalitpur Metropolitan City" },
    { value: "mahalaxmi", label: "Mahalaxmi Municipality" },
    { value: "godawari", label: "Godawari Municipality" },
    { value: "konjyosom", label: "Konjyosom Rural Municipality" },
    { value: "bagmati", label: "Bagmati Rural Municipality" },
    { value: "mahankal", label: "Mahankal Rural Municipality" },
  ],
  bhaktapur: [
    { value: "bhaktapur", label: "Bhaktapur Municipality" },
    { value: "madhyapur_thimi", label: "Madhyapur Thimi Municipality" },
    { value: "suryabinayak", label: "Suryabinayak Municipality" },
    { value: "changunarayan", label: "Changunarayan Municipality" },
  ],
  chitwan: [
    { value: "bharatpur", label: "Bharatpur Metropolitan City" },
    { value: "kalika", label: "Kalika Municipality" },
    { value: "khairahani", label: "Khairahani Municipality" },
    { value: "madi", label: "Madi Municipality" },
    { value: "ratnanagar", label: "Ratnanagar Municipality" },
    { value: "rapti", label: "Rapti Municipality" },
    { value: "ichchhakamana", label: "Ichchhakamana Rural Municipality" },
  ],
  taplejung: [
    { value: "phungling", label: "Phungling Municipality" },
    { value: "miklung", label: "Miklung Rural Municipality" },
    { value: "phaktanglung", label: "Phaktanglung Rural Municipality" },
    { value: "sidingwa", label: "Sidingwa Rural Municipality" },
    { value: "maikwakhola", label: "Maiwakhola Rural Municipality" },
    { value: "pathibhara_yangwarak", label: "Pathibhara Yangwarak Rural Municipality" }
  ],
  sankhuwasabha: [
    { value: "khandbari", label: "Khandbari Municipality" },
    { value: "chainpur", label: "Chainpur Municipality" },
    { value: "dharmadevi", label: "Dharmadevi Municipality" },
    { value: "panchkhapan", label: "Panchkhapan Municipality" },
    { value: "sabhapokhari", label: "Sabhapokhari Rural Municipality" },
    { value: "chingla", label: "Chichila Rural Municipality" },
    { value: "makalu", label: "Makalu Rural Municipality" },
    { value: "silichong", label: "Silichong Rural Municipality" }
  ],
  solukhumbu: [
    { value: "solududhkunda", label: "Solududhkunda Municipality" },
    { value: "khumbu_pasang_lhamu", label: "Khumbu Pasang Lhamu Rural Municipality" },
    { value: "mahakulung", label: "Mahakulung Rural Municipality" },
    { value: "sotang", label: "Sotang Rural Municipality" },
    { value: "necha_salyan", label: "Necha Salyan Rural Municipality" },
    { value: "thulung_dudh_koshi", label: "Thulung Dudhkoshi Rural Municipality" }
  ],
  okhaldhunga: [
    { value: "okhaldhunga", label: "Okhaldhunga Municipality" },
    { value: "siddhicharan", label: "Siddhicharan Municipality" },
    { value: "champadevi", label: "Champadevi Rural Municipality" },
    { value: "chishankhugadhi", label: "Chishankhugadhi Rural Municipality" },
    { value: "likhu", label: "Likhu Rural Municipality" },
    { value: "manebhanjyang", label: "Manebhanjyang Rural Municipality" },
    { value: "molung", label: "Molung Rural Municipality" },
    { value: "sunkoshi", label: "Sunkoshi Rural Municipality" }
  ],
  khotang: [
    { value: "diktel_rupakot_majakchhi", label: "Diktel Rupakot Majhuwagadhi Municipality" },
    { value: "halesi_tuwachung", label: "Halesi Tuwachung Municipality" },
    { value: "barahapokhari", label: "Barahapokhari Rural Municipality" },
    { value: "jalpa", label: "Jalpa Rural Municipality" },
    { value: "khotehang", label: "Khotehang Rural Municipality" },
    { value: "kepilasgadhi", label: "Kepilasgadhi Rural Municipality" },
    { value: "rawa_besi", label: "Rawa Besi Rural Municipality" },
    { value: "sakhuwasabha", label: "Sakela Rural Municipality" }
  ],
  bhojpur: [
    { value: "bhojpur", label: "Bhojpur Municipality" },
    { value: "shadananda", label: "Shadananda Municipality" },
    { value: "ramprasad_rai", label: "Ramprasad Rai Rural Municipality" },
    { value: "temkemaiyung", label: "Temkemaiyung Rural Municipality" },
    { value: "salpasilichho", label: "Salpasilichho Rural Municipality" },
    { value: "arun", label: "Arun Rural Municipality" },
    { value: "aamchowk", label: "Aamchowk Rural Municipality" },
    { value: "hatuwagadhi", label: "Hatuwagadhi Rural Municipality" }
  ],
  dhankuta: [
    { value: "dhankuta", label: "Dhankuta Municipality" },
    { value: "pakhribas", label: "Pakhribas Municipality" },
    { value: "chhathar_jorpati", label: "Chhathar Jorpati Rural Municipality" },
    { value: "sangurigadhi", label: "Sangurigadhi Rural Municipality" },
    { value: "shahidbhumi", label: "Shahidbhumi Rural Municipality" },
    { value: "mahalaxmi", label: "Mahalaxmi Rural Municipality" },
    { value: "chaubise", label: "Chaubise Rural Municipality" }
  ],
  terhathum: [
    { value: "myanglung", label: "Myanglung Municipality" },
    { value: "laligurans", label: "Laligurans Municipality" },
    { value: "phedap", label: "Phedap Rural Municipality" },
    { value: "menchhayayem", label: "Menchhayayem Rural Municipality" },
    { value: "chhathar", label: "Chhathar Rural Municipality" }
  ],
  panchthar: [
    { value: "phidim", label: "Phidim Municipality" },
    { value: "falelung", label: "Falelung Rural Municipality" },
    { value: "falgunanda", label: "Falgunanda Rural Municipality" },
    { value: "hilihang", label: "Hilihang Rural Municipality" },
    { value: "miklung", label: "Miklajung Rural Municipality" },
    { value: "tumbewa", label: "Tumbewa Rural Municipality" },
    { value: "kummayak", label: "Kummayak Rural Municipality" }
  ],
  ilam: [
    { value: "ilam", label: "Ilam Municipality" },
    { value: "deumai", label: "Deumai Municipality" },
    { value: "maijogmai", label: "Maijogmai Rural Municipality" },
    { value: "chulachuli", label: "Chulachuli Rural Municipality" },
    { value: "fakphokthum", label: "Fakphokthum Rural Municipality" },
    { value: "mangsebung", label: "Mangsebung Rural Municipality" },
    { value: "roknarayan", label: "Rong Rural Municipality" },
    { value: "sandakpur", label: "Sandakpur Rural Municipality" },
    { value: "suryodaya", label: "Suryodaya Municipality" }
  ],
  jhapa: [
    { value: "birtamod", label: "Birtamod Municipality" },
    { value: "mechinagar", label: "Mechinagar Municipality" },
    { value: "damak", label: "Damak Municipality" },
    { value: "kankai", label: "Kankai Municipality" },
    { value: "shivasatakshi", label: "Shivasatakshi Municipality" },
    { value: "gauradaha", label: "Gauradaha Municipality" },
    { value: "gauriganj", label: "Gauriganj Rural Municipality" },
    { value: "barhadashi", label: "Barhadashi Rural Municipality" },
    { value: "buddhashanti", label: "Buddhashanti Rural Municipality" },
    { value: "kamal", label: "Kamal Rural Municipality" },
    { value: "jhapa_rural", label: "Jhapa Rural Municipality" },
    { value: "haldibari", label: "Haldibari Rural Municipality" }
  ],
  morang: [
    { value: "biratnagar", label: "Biratnagar Metropolitan City" },
    { value: "belbari", label: "Belbari Municipality" },
    { value: "letang", label: "Letang Municipality" },
    { value: "pathari_shanishchare", label: "Pathari Shanishchare Municipality" },
    { value: "ratuwamai", label: "Ratuwamai Municipality" },
    { value: "sundarharaicha", label: "Sundarharaicha Municipality" },
    { value: "urlabari", label: "Urlabari Municipality" },
    { value: "buddhiganga", label: "Buddhiganga Rural Municipality" },
    { value: "dhanpalthan", label: "Dhanpalthan Rural Municipality" },
    { value: "jahada", label: "Jahada Rural Municipality" },
    { value: "kanepokhari", label: "Kanepokhari Rural Municipality" },
    { value: "kerabari", label: "Kerabari Rural Municipality" },
    { value: "miklagunj", label: "Miklajung Rural Municipality" }
  ],
  sunsari: [
    { value: "inaruwa", label: "Inaruwa Municipality" },
    { value: "itahari", label: "Itahari Sub-Metropolitan City" },
    { value: "dharan", label: "Dharan Sub-Metropolitan City" },
    { value: "duhabi", label: "Duhabi Municipality" },
    { value: "ramdhuni", label: "Ramdhuni Municipality" },
    { value: "barahachhetra", label: "Barahachhetra Municipality" },
    { value: "bishnupaduka", label: "Bishnupaduka Rural Municipality" },
    { value: "bhokraha_narsingh", label: "Bhokraha Narsingh Rural Municipality" },
    { value: "deba_saran", label: "Dewangunj Rural Municipality" },
    { value: "koshi", label: "Koshi Rural Municipality" },
    { value: "gadhi", label: "Gadhi Rural Municipality" },
    { value: "harinagara", label: "Harinagara Rural Municipality" },
    { value: "barju", label: "Barju Rural Municipality" }
  ],
  udayapur: [
    { value: "gaighat", label: "Triyuga Municipality" },
    { value: "belaka", label: "Belaka Municipality" },
    { value: "chaudandigadhi", label: "Chaudandigadhi Municipality" },
    { value: "raluwa", label: "Rautamai Rural Municipality" },
    { value: "tapli", label: "Tapli Rural Municipality" },
    { value: "udayapurgadhi", label: "Udayapurgadhi Rural Municipality" }
  ],
  saptari: [
    { value: "rajbiraj", label: "Rajbiraj Municipality" },
    { value: "kanchanrup", label: "Kanchanrup Municipality" },
    { value: "surunga", label: "Surunga Municipality" },
    { value: "hanumannagar_kankalini", label: "Hanumannagar Kankalini Municipality" },
    { value: "belhi_chapena", label: "Belhi Chapena Rural Municipality" },
    { value: "bodebarsain", label: "Bodebarsain Municipality" },
    { value: "chhinnamasta", label: "Chhinnamasta Rural Municipality" },
    { value: "mahadeva", label: "Mahadeva Rural Municipality" },
    { value: "saptakoshi", label: "Saptakoshi Rural Municipality" },
    { value: "tilathi_koiladi", label: "Tilathi Koiladi Rural Municipality" },
    { value: "agnisair_krishnasavaran", label: "Agnisair Krishnasavaran Rural Municipality" },
    { value: "tirahut", label: "Tirahut Rural Municipality" }
  ],
  siraha: [
    { value: "siraha", label: "Siraha Municipality" },
    { value: "lahan", label: "Lahan Municipality" },
    { value: "dhangadhimai", label: "Dhangadhimai Municipality" },
    { value: "golbazar", label: "Golbazar Municipality" },
    { value: "mirchaiya", label: "Mirchaiya Municipality" },
    { value: "naraha", label: "Naraha Rural Municipality" },
    { value: "aurahi", label: "Aurahi Rural Municipality" },
    { value: "bishnupur", label: "Bishnupur Rural Municipality" },
    { value: "sakhuwanankarkatti", label: "Sakhuwanankarkatti Rural Municipality" },
    { value: "sukhipur", label: "Sukhipur Rural Municipality" },
    { value: "karjanha", label: "Karjanha Municipality" },
    { value: "arnama", label: "Arnama Rural Municipality" }
  ],
  dhanusa: [
    { value: "janakpur", label: "Janakpur Sub-Metropolitan City" },
    { value: "dhanushadham", label: "Dhanushadham Municipality" },
    { value: "ganeshman_charanath", label: "Ganeshman Charanath Municipality" },
    { value: "kamala", label: "Kamala Municipality" },
    { value: "mukhiyapatti_musaharniya", label: "Mukhiyapatti Musaharniya Rural Municipality" },
    { value: "bateshwar", label: "Bateshwar Rural Municipality" },
    { value: "dhanauji", label: "Dhanauji Rural Municipality" },
    { value: "janaknandani", label: "Janaknandani Rural Municipality" },
    { value: "sabaila", label: "Sabaila Municipality" },
    { value: "shahidnagar", label: "Shahidnagar Municipality" },
    { value: "aurahi", label: "Aurahi Municipality" },
    { value: "bideha", label: "Bideha Municipality" }
  ],
  mahottari: [
    { value: "jaleshwar", label: "Jaleshwar Municipality" },
    { value: "bardibas", label: "Bardibas Municipality" },
    { value: "aurahi", label: "Aurahi Municipality" },
    { value: "balwa", label: "Balwa Municipality" },
    { value: "loharpatti", label: "Loharpatti Municipality" },
    { value: "ramgopalpur", label: "Ramgopalpur Municipality" },
    { value: "ekdara", label: "Ekdara Rural Municipality" },
    { value: "manara_shiswa", label: "Manara Shiswa Municipality" },
    { value: "pipra", label: "Pipra Rural Municipality" },
    { value: "samsi", label: "Samsi Rural Municipality" },
    { value: "sonama", label: "Sonama Rural Municipality" }
  ],
  sarlahi: [
    { value: "malangwa", label: "Malangwa Municipality" },
    { value: "barahathawa", label: "Barahathawa Municipality" },
    { value: "balara", label: "Balara Municipality" },
    { value: "haripur", label: "Haripur Municipality" },
    { value: "ishworpur", label: "Ishworpur Municipality" },
    { value: "kabilasi", label: "Kabilasi Municipality" },
    { value: "lalbandi", label: "Lalbandi Municipality" },
    { value: "godaita", label: "Godaita Municipality" },
    { value: "basbariya", label: "Basbariya Rural Municipality" },
    { value: "brahm_puri", label: "Bramhpuri Rural Municipality" },
    { value: "chakraghatta", label: "Chakraghatta Rural Municipality" },
    { value: "kaudena", label: "Kaudena Rural Municipality" },
    { value: "parsa", label: "Parsa Rural Municipality" }
  ],
  rautahat: [
    { value: "gaur", label: "Gaur Municipality" },
    { value: "garuda", label: "Garuda Municipality" },
    { value: "chandrapur", label: "Chandrapur Municipality" },
    { value: "dewadhi", label: "Dewahi Gonahi Municipality" },
    { value: "fatuwa_mahanaur", label: "Fatuwa Maheshpur Municipality" },
    { value: "isnath", label: "Ishanath Municipality" },
    { value: "madav_narayan", label: "Madhav Narayan Municipality" },
    { value: "maulapur", label: "Maulapur Municipality" },
    { value: "phatuwa_mahanaur", label: "Phatuwa Maheshpur Municipality" },
    { value: "rajdevi", label: "Rajdevi Municipality" },
    { value: "durga_bhagwati", label: "Durga Bhagwati Rural Municipality" },
    { value: "gadhimai", label: "Gadhimai Rural Municipality" },
    { value: "katahariya", label: "Katahariya Municipality" },
    { value: "yamunamai", label: "Yamunamai Rural Municipality" }
  ],
  bara: [
    { value: "kalaiya", label: "Kalaiya Sub-Metropolitan City" },
    { value: "jeetpur_simara", label: "Jeetpur Simara Sub-Metropolitan City" },
    { value: "kolhabi", label: "Kolhabi Municipality" },
    { value: "parwanipur", label: "Parwanipur Rural Municipality" },
    { value: "prasauni", label: "Prasauni Rural Municipality" },
    { value: "pheta", label: "Pheta Rural Municipality" },
    { value: "bishrampur", label: "Bishrampur Rural Municipality" },
    { value: "karaiyamai", label: "Karaiyamai Rural Municipality" },
    { value: "simraungadh", label: "Simraungadh Municipality" },
    { value: "subarna", label: "Subarna Rural Municipality" },
    { value: "adarskotwal", label: "Adarsha Kotwal Rural Municipality" },
    { value: "mahagadhimai", label: "Mahagadhimai Municipality" }
  ],
  parsa: [
    { value: "birgunj", label: "Birgunj Metropolitan City" },
    { value: "pokhariya", label: "Pokhariya Municipality" },
    { value: "bahudarmai", label: "Bahudarmai Municipality" },
    { value: "bindabasini", label: "Bindabasini Rural Municipality" },
    { value: "chhipaharmai", label: "Chhipaharmai Rural Municipality" },
    { value: "jagarnathpur", label: "Jagarnathpur Rural Municipality" },
    { value: "pakaha_mainpur", label: "Pakaha Mainpur Rural Municipality" },
    { value: "paterwa_sugauli", label: "Paterwa Sugauli Rural Municipality" },
    { value: "sakhuwa_prasauni", label: "Sakhuwa Prasauni Rural Municipality" },
    { value: "thori", label: "Thori Rural Municipality" },
    { value: "biruwa_guthi", label: "Biruwa Guthi Rural Municipality" },
    { value: "parwanipur", label: "Parwanipur Rural Municipality" }
  ],
  dolakha: [
    { value: "bhimeshwor", label: "Bhimeshwor Municipality" },
    { value: "bigu", label: "Bigu Rural Municipality" },
    { value: "gaurishankar", label: "Gaurishankar Rural Municipality" },
    { value: "jiri", label: "Jiri Municipality" },
    { value: "kalinchowk", label: "Kalinchowk Rural Municipality" },
    { value: "melung", label: "Melung Rural Municipality" },
    { value: "shailung", label: "Shailung Rural Municipality" }
  ],
  sindhupalchok: [
    { value: "chautara_sangachowkgadi", label: "Chautara Sangachowkgadi Municipality" },
    { value: "bahrabise", label: "Bahrabise Municipality" },
    { value: "melamchi", label: "Melamchi Municipality" },
    { value: "balefi", label: "Balefi Rural Municipality" },
    { value: "helambu", label: "Helambu Rural Municipality" },
    { value: "indrawati", label: "Indrawati Rural Municipality" },
    { value: "jangal", label: "Jugal Rural Municipality" },
    { value: "lisankhu_pakhar", label: "Lisankhu Pakhar Rural Municipality" },
    { value: "panchpokhari_thangpal", label: "Panchpokhari Thangpal Rural Municipality" },
    { value: "sunkoshi", label: "Sunkoshi Rural Municipality" },
    { value: "tripurasundari", label: "Tripurasundari Rural Municipality" }
  ],
  rasuwa: [
    { value: "gosaikunda", label: "Gosaikunda Rural Municipality" },
    { value: "naukunda", label: "Naukunda Rural Municipality" },
    { value: "kalika", label: "Kalika Rural Municipality" },
    { value: "uttargaya", label: "Uttargaya Rural Municipality" }
  ],
  dhading: [
    { value: "dhading", label: "Dhading Municipality" },
    { value: "naubise", label: "Naubise Rural Municipality" },
    { value: "benighat_rorang", label: "Benighat Rorang Rural Municipality" },
    { value: "gajuri", label: "Gajuri Rural Municipality" },
    { value: "galchhi", label: "Galchhi Rural Municipality" },
    { value: "jangal", label: "Jwalamukhi Rural Municipality" },
    { value: "khaniyabas", label: "Khaniyabas Rural Municipality" },
    { value: "netrawati_dabjong", label: "Netrawati Dabjong Rural Municipality" },
    { value: "rubivalley", label: "Rubivalley Rural Municipality" },
    { value: "siddhalek", label: "Siddhalek Rural Municipality" },
    { value: "thakre", label: "Thakre Rural Municipality" },
    { value: "tripurasundari", label: "Tripurasundari Rural Municipality" }
  ],
  nuwakot: [
    { value: "bidur", label: "Bidur Municipality" },
    { value: "belkotgadhi", label: "Belkotgadhi Municipality" },
    { value: "kakani", label: "Kakani Rural Municipality" },
    { value: "kispang", label: "Kispang Rural Municipality" },
    { value: "likhu", label: "Likhu Rural Municipality" },
    { value: "meghang", label: "Meghang Rural Municipality" },
    { value: "panchakanya", label: "Panchakanya Rural Municipality" },
    { value: "suryagadhi", label: "Suryagadhi Rural Municipality" },
    { value: "tadi", label: "Tadi Rural Municipality" },
    { value: "tarakeshwor", label: "Tarakeshwor Rural Municipality" }
  ],
  kavrepalanchok: [
    { value: "dhulikhel", label: "Dhulikhel Municipality" },
    { value: "banepa", label: "Banepa Municipality" },
    { value: "panauti", label: "Panauti Municipality" },
    { value: "namobuddha", label: "Namobuddha Municipality" },
    { value: "mandandeupur", label: "Mandandeupur Municipality" },
    { value: "bhumlu", label: "Bhumlu Rural Municipality" },
    { value: "chaurideurali", label: "Chaurideurali Rural Municipality" },
    { value: "khani_kharka", label: "Khanikharka Rural Municipality" },
    { value: "mahankal", label: "Mahankal Rural Municipality" },
    { value: "panchkhal", label: "Panchkhal Municipality" },
    { value: "roshi", label: "Roshi Rural Municipality" }
  ],
  ramechhap: [
    { value: "manthali", label: "Manthali Municipality" },
    { value: "umakunda", label: "Umakunda Rural Municipality" },
    { value: "khadadevi", label: "Khadadevi Rural Municipality" },
    { value: "likhu_tamakoshi", label: "Likhu Tamakoshi Rural Municipality" },
    { value: "doramba_shailung", label: "Doramba Shailung Rural Municipality" },
    { value: "gokulganga", label: "Gokulganga Rural Municipality" },
    { value: "khandadevi", label: "Khandadevi Rural Municipality" }
  ],
  sindhuli: [
    { value: "kamalamai", label: "Kamalamai Municipality" },
    { value: "dudhauli", label: "Dudhauli Municipality" },
    { value: "ghangha", label: "Ghangha Rural Municipality" },
    { value: "hariharpurgadhi", label: "Hariharpurgadhi Rural Municipality" },
    { value: "marin", label: "Marin Rural Municipality" },
    { value: "phikkal", label: "Phikkal Rural Municipality" },
    { value: "sunkoshi", label: "Sunkoshi Rural Municipality" },
    { value: "tinpatan", label: "Tinpatan Rural Municipality" }
  ],
  makawanpur: [
    { value: "hetauda", label: "Hetauda Sub-Metropolitan City" },
    { value: "bhimphedi", label: "Bhimphedi Rural Municipality" },
    { value: "bakaiya", label: "Bakaiya Rural Municipality" },
    { value: "indrasarowar", label: "Indrasarowar Rural Municipality" },
    { value: "kailash", label: "Kailash Rural Municipality" },
    { value: "manahari", label: "Manahari Rural Municipality" },
    { value: "raksirang", label: "Raksirang Rural Municipality" },
    { value: "thaha", label: "Thaha Municipality" }
  ],
  gorkha: [
    { value: "gorkha", label: "Gorkha Municipality" },
    { value: "palungtar", label: "Palungtar Municipality" },
    { value: "aarughat", label: "Aarughat Rural Municipality" },
    { value: "ajirkot", label: "Ajirkot Rural Municipality" },
    { value: "bhimsen", label: "Bhimsen Rural Municipality" },
    { value: "chumnubri", label: "Chumnubri Rural Municipality" },
    { value: "dharche", label: "Dharche Rural Municipality" },
    { value: "gandaki", label: "Gandaki Rural Municipality" },
    { value: "sahid_lakhan", label: "Sahid Lakhan Rural Municipality" },
    { value: "siranchok", label: "Siranchok Rural Municipality" }
  ],
  manang: [
    { value: "chame", label: "Chame Rural Municipality" },
    { value: "nashong", label: "Nashong Rural Municipality" },
    { value: "narpa", label: "Narpa Rural Municipality" },
    { value: "ngisyang", label: "Ngisyang Rural Municipality" }
  ],
  mustang: [
    { value: "jomsom", label: "Gharapjhong Rural Municipality" },
    { value: "lo_ghekar_damodarkunda", label: "Lo-Ghekar Damodarkunda Rural Municipality" },
    { value: "lo_manthang", label: "Lo-Manthang Rural Municipality" },
    { value: "thasang", label: "Thasang Rural Municipality" },
    { value: "waragung_muktichhetra", label: "Waragung Muktichhetra Rural Municipality" }
  ],
  myagdi: [
    { value: "beni", label: "Beni Municipality" },
    { value: "annapurna", label: "Annapurna Rural Municipality" },
    { value: "dana", label: "Dana Rural Municipality" },
    { value: "malika", label: "Malika Rural Municipality" },
    { value: "mangala", label: "Mangala Rural Municipality" },
    { value: "rukum", label: "Raghuganga Rural Municipality" }
  ],
  kaski: [
    { value: "pokhara", label: "Pokhara Metropolitan City" },
    { value: "annapurna", label: "Annapurna Rural Municipality" },
    { value: "machhapuchchhre", label: "Machhapuchchhre Rural Municipality" },
    { value: "madi", label: "Madi Rural Municipality" },
    { value: "rupa", label: "Rupa Rural Municipality" }
  ],
  lamjung: [
    { value: "besishahar", label: "Besishahar Municipality" },
    { value: "dordi", label: "Dordi Rural Municipality" },
    { value: "kwholasothar", label: "Kwholasothar Rural Municipality" },
    { value: "madhya_nepal", label: "Madhya Nepal Municipality" },
    { value: "rainas", label: "Rainas Municipality" },
    { value: "sundarbazar", label: "Sundarbazar Municipality" },
    { value: "marsyangdi", label: "Marsyangdi Rural Municipality" }
  ],
  tanahu: [
    { value: "byas", label: "Byas Municipality" },
    { value: "shuklagandaki", label: "Shuklagandaki Municipality" },
    { value: "bhanu", label: "Bhanu Municipality" },
    { value: "bandipur", label: "Bandipur Rural Municipality" },
    { value: "ghiring", label: "Ghiring Rural Municipality" },
    { value: "devghat", label: "Devghat Rural Municipality" },
    { value: "myagde", label: "Myagde Rural Municipality" },
    { value: "rishing", label: "Rishing Rural Municipality" },
    { value: "satyawati", label: "Satyawati Rural Municipality" }
  ],
  nawalparasi_east: [
    { value: "gaindakot", label: "Gaindakot Municipality" },
    { value: "bulingtar", label: "Bulingtar Rural Municipality" },
    { value: "binayi_triveni", label: "Binayi Triveni Rural Municipality" },
    { value: "hupsekot", label: "Hupsekot Rural Municipality" },
    { value: "baudikali", label: "Baudikali Rural Municipality" },
    { value: "devchuli", label: "Devchuli Municipality" },
    { value: "kawasoti", label: "Kawasoti Municipality" }
  ],
  syangja: [
    { value: "putalibazar", label: "Putalibazar Municipality" },
    { value: "bhirkot", label: "Bhirkot Municipality" },
    { value: "chapakot", label: "Chapakot Municipality" },
    { value: "walling", label: "Walling Municipality" },
    { value: "galyang", label: "Galyang Municipality" },
    { value: "arjun_chaupari", label: "Arjun Chaupari Rural Municipality" },
    { value: "biruwa", label: "Biruwa Rural Municipality" },
    { value: "harinas", label: "Harinas Rural Municipality" },
    { value: "kaligandaki", label: "Kaligandaki Rural Municipality" },
    { value: "phedikhola", label: "Phedikhola Rural Municipality" }
  ],
  parbat: [
    { value: "kusma", label: "Kusma Municipality" },
    { value: "phalebas", label: "Phalebas Municipality" },
    { value: "jaljala", label: "Jaljala Rural Municipality" },
    { value: "paiyun", label: "Paiyun Rural Municipality" },
    { value: "mawang", label: "Mahashila Rural Municipality" },
    { value: "modi", label: "Modi Rural Municipality" },
    { value: "bihadi", label: "Bihadi Rural Municipality" }
  ],
  baglung: [
    { value: "baglung", label: "Baglung Municipality" },
    { value: "jaimini", label: "Jaimini Municipality" },
    { value: "galkot", label: "Galkot Municipality" },
    { value: "dhorpatan", label: "Dhorpatan Municipality" },
    { value: "badigad", label: "Badigad Rural Municipality" },
    { value: "bareng", label: "Bareng Rural Municipality" },
    { value: "khathekhola", label: "Khathekhola Rural Municipality" },
    { value: "nishikhola", label: "Nishikhola Rural Municipality" },
    { value: "tamankhola", label: "Tamankhola Rural Municipality" },
    { value: "tarakhola", label: "Tarakhola Rural Municipality" }
  ],
  rukum_east: [
    { value: "bhume", label: "Bhume Rural Municipality" },
    { value: "putha_uttarganga", label: "Putha Uttarganga Rural Municipality" },
    { value: "sisne", label: "Sisne Rural Municipality" }
  ],
  rolpa: [
    { value: "liwang", label: "Liwang Municipality" },
    { value: "lungri", label: "Lungri Rural Municipality" },
    { value: "madi", label: "Madi Rural Municipality" },
    { value: "pariwartan", label: "Pariwartan Rural Municipality" },
    { value: "runtigadhi", label: "Runtigadhi Rural Municipality" },
    { value: "sunchhahari", label: "Sunchhahari Rural Municipality" },
    { value: "thawang", label: "Thawang Rural Municipality" }
  ],
  pyuthan: [
    { value: "pyuthan", label: "Pyuthan Municipality" },
    { value: "gaumukhi", label: "Gaumukhi Rural Municipality" },
    { value: "jhimruk", label: "Jhimruk Rural Municipality" },
    { value: "mandavi", label: "Mandavi Rural Municipality" },
    { value: "mallarani", label: "Mallarani Rural Municipality" },
    { value: "naubahini", label: "Naubahini Rural Municipality" },
    { value: "sarumarani", label: "Sarumarani Rural Municipality" },
    { value: "swargadwari", label: "Swargadwari Rural Municipality" }
  ],
  gulmi: [
    { value: "resunga", label: "Resunga Municipality" },
    { value: "ishma", label: "Ishma Rural Municipality" },
    { value: "kaligandaki", label: "Kaligandaki Rural Municipality" },
    { value: "madane", label: "Madane Rural Municipality" },
    { value: "malika", label: "Malika Rural Municipality" },
    { value: "musikot", label: "Musikot Municipality" },
    { value: "satyawati", label: "Satyawati Rural Municipality" },
    { value: "chhatrakot", label: "Chhatrakot Rural Municipality" },
    { value: "dhurkot", label: "Dhurkot Rural Municipality" }
  ],
  arghakhanchi: [
    { value: "sandhikharka", label: "Sandhikharka Municipality" },
    { value: "chhatradev", label: "Chhatradev Rural Municipality" },
    { value: "murtibang", label: "Murtibang Rural Municipality" },
    { value: "panini", label: "Panini Rural Municipality" },
    { value: "shitaganga", label: "Shitaganga Municipality" }
  ],
  palpa: [
    { value: "tansen", label: "Tansen Municipality" },
    { value: "rambha", label: "Rambha Rural Municipality" },
    { value: "rainadevi_chhahara", label: "Rainadevi Chhahara Rural Municipality" },
    { value: "ribdikot", label: "Ribdikot Rural Municipality" },
    { value: "satyawati", label: "Satyawati Rural Municipality" },
    { value: "tinau", label: "Tinau Rural Municipality" },
    { value: "bagnaskali", label: "Bagnaskali Rural Municipality" },
    { value: "mathagadhi", label: "Mathagadhi Rural Municipality" },
    { value: "purbakhola", label: "Purbakhola Rural Municipality" }
  ],
  nawalparasi_west: [
    { value: "bardaghat", label: "Bardaghat Municipality" },
    { value: "ramgram", label: "Ramgram Municipality" },
    { value: "sunwal", label: "Sunwal Municipality" },
    { value: "palhinandan", label: "Palhinandan Rural Municipality" },
    { value: "pratappur", label: "Pratappur Rural Municipality" },
    { value: "sarawal", label: "Sarawal Rural Municipality" },
    { value: "susta", label: "Susta Rural Municipality" }
  ],
  rupandehi: [
    { value: "butwal", label: "Butwal Sub-Metropolitan City" },
    { value: "siddharthanagar", label: "Siddharthanagar Municipality" },
    { value: "devdaha", label: "Devdaha Municipality" },
    { value: "lumbini_sanskritik", label: "Lumbini Sanskritik Municipality" },
    { value: "sainamaina", label: "Sainamaina Municipality" },
    { value: "tilottama", label: "Tilottama Municipality" },
    { value: "gaidhawa", label: "Gaidhawa Rural Municipality" },
    { value: "kothimai", label: "Kothimai Rural Municipality" },
    { value: "marchawari", label: "Marchawari Rural Municipality" },
    { value: "omsatiya", label: "Omsatiya Rural Municipality" },
    { value: "rohini", label: "Rohini Rural Municipality" },
    { value: "siyari", label: "Siyari Rural Municipality" },
    { value: "suddhodhan", label: "Suddhodhan Rural Municipality" }
  ],
  kapilvastu: [
    { value: "taulihawa", label: "Kapilvastu Municipality" },
    { value: "banganga", label: "Banganga Municipality" },
    { value: "krishnanagar", label: "Krishnanagar Municipality" },
    { value: "maharajgunj", label: "Maharajgunj Municipality" },
    { value: "shivaraj", label: "Shivaraj Municipality" },
    { value: "bijaynagar", label: "Bijaynagar Rural Municipality" },
    { value: "mayadevi", label: "Mayadevi Rural Municipality" },
    { value: "yasodhara", label: "Yasodhara Rural Municipality" },
    { value: "budhi", label: "Budhi Rural Municipality" }
  ],
  dang: [
    { value: "ghorahi", label: "Ghorahi Sub-Metropolitan City" },
    { value: "tulsipur", label: "Tulsipur Sub-Metropolitan City" },
    { value: "lamahi", label: "Lamahi Municipality" },
    { value: "bangaun", label: "Bangau Rural Municipality" },
    { value: "dangisharan", label: "Dangisharan Rural Municipality" },
    { value: "gadhawa", label: "Gadhawa Rural Municipality" },
    { value: "rapti", label: "Rapti Rural Municipality" },
    { value: "shantinagar", label: "Shantinagar Rural Municipality" }
  ],
  banke: [
    { value: "nepalgunj", label: "Nepalgunj Sub-Metropolitan City" },
    { value: "kohalpur", label: "Kohalpur Municipality" },
    { value: "baijanath", label: "Baijanath Rural Municipality" },
    { value: "duduwa", label: "Duduwa Rural Municipality" },
    { value: "janaki", label: "Janaki Rural Municipality" },
    { value: "khajura", label: "Khajura Rural Municipality" },
    { value: "narainapur", label: "Narainapur Rural Municipality" },
    { value: "rapti_sonari", label: "Rapti Sonari Rural Municipality" }
  ],
  bardiya: [
    { value: "gulariya", label: "Gulariya Municipality" },
    { value: "madhuwan", label: "Madhuwan Municipality" },
    { value: "thakurbaba", label: "Thakurbaba Municipality" },
    { value: "barbardiya", label: "Barbardiya Municipality" },
    { value: "basgadhi", label: "Basgadhi Municipality" },
    { value: "badhaiyatal", label: "Badhaiyatal Rural Municipality" },
    { value: "geruwa", label: "Geruwa Rural Municipality" },
    { value: "rajapur", label: "Rajapur Municipality" }
  ],
  dolpa: [
    { value: "thulibheri", label: "Thulibheri Municipality" },
    { value: "tripurasundari", label: "Tripurasundari Municipality" },
    { value: "chharka_tangsong", label: "Chharka Tangsong Rural Municipality" },
    { value: "jagadal", label: "Jagadulla Rural Municipality" },
    { value: "mudkechula", label: "Mudkechula Rural Municipality" },
    { value: "shey_phoksundo", label: "Shey Phoksundo Rural Municipality" }
  ],
  mugu: [
    { value: "chhayanath_rara", label: "Chhayanath Rara Municipality" },
    { value: "khatyad", label: "Khatyad Rural Municipality" },
    { value: "mugum_karmarong", label: "Mugum Karmarong Rural Municipality" },
    { value: "soru", label: "Soru Rural Municipality" }
  ],
  humla: [
    { value: "simkot", label: "Simkot Rural Municipality" },
    { value: "chankheli", label: "Chankheli Rural Municipality" },
    { value: "adanchuli", label: "Adanchuli Rural Municipality" },
    { value: "kharpunath", label: "Kharpunath Rural Municipality" },
    { value: "sarkegad", label: "Sarkegad Rural Municipality" },
    { value: "tanjakot", label: "Tanjakot Rural Municipality" }
  ],
  jumla: [
    { value: "chandannath", label: "Chandannath Municipality" },
    { value: "guthichaur", label: "Guthichaur Rural Municipality" },
    { value: "hima", label: "Hima Rural Municipality" },
    { value: "kanakasundari", label: "Kanakasundari Rural Municipality" },
    { value: "patrasi", label: "Patrasi Rural Municipality" },
    { value: "sinja", label: "Sinja Rural Municipality" },
    { value: "tatopani", label: "Tatopani Rural Municipality" }
  ],
  kalikot: [
    { value: "naraharinath", label: "Naraharinath Rural Municipality" },
    { value: "pachaljharana", label: "Pachaljharana Rural Municipality" },
    { value: "palata", label: "Palata Rural Municipality" },
    { value: "raskot", label: "Raskot Municipality" },
    { value: "sanni_triveni", label: "Sanni Triveni Rural Municipality" },
    { value: "tilagufa", label: "Tilagufa Municipality" },
    { value: "mahawai", label: "Mahawai Rural Municipality" }
  ],
  dailekh: [
    { value: "narayan", label: "Narayan Municipality" },
    { value: "dullu", label: "Dullu Municipality" },
    { value: "bhairabi", label: "Bhairabi Rural Municipality" },
    { value: "gurans", label: "Gurans Rural Municipality" },
    { value: "mahabu", label: "Mahabu Rural Municipality" },
    { value: "naumule", label: "Naumule Rural Municipality" },
    { value: "thantikandh", label: "Thantikandh Rural Municipality" }
  ],
  jajarkot: [
    { value: "bheri", label: "Bheri Municipality" },
    { value: "chhedagad", label: "Chhedagad Municipality" },
    { value: "junichande", label: "Junichande Rural Municipality" },
    { value: "kuse", label: "Kuse Rural Municipality" },
    { value: "shivalaya", label: "Shivalaya Rural Municipality" }
  ],
  rukum_west: [
    { value: "musikot", label: "Musikot Municipality" },
    { value: "chaurjahari", label: "Chaurjahari Municipality" },
    { value: "aathbiskot", label: "Aathbiskot Municipality" },
    { value: "banphikot", label: "Banphikot Rural Municipality" },
    { value: "sanibheri", label: "Sanibheri Rural Municipality" },
    { value: "triveni", label: "Triveni Rural Municipality" }
  ],
  salyan: [
    { value: "sharad", label: "Sharada Municipality" },
    { value: "bangad_kupinde", label: "Bangad Kupinde Municipality" },
    { value: "chhatreshwori", label: "Chhatreshwori Rural Municipality" },
    { value: "darma", label: "Darma Rural Municipality" },
    { value: "kavre", label: "Kavre Rural Municipality" },
    { value: "kumakh", label: "Kumakh Rural Municipality" },
    { value: "siddhakumakh", label: "Siddhakumakh Rural Municipality" },
    { value: "triveni", label: "Triveni Rural Municipality" }
  ],
  surkhet: [
    { value: "birendranagar", label: "Birendranagar Municipality" },
    { value: "gurbhakot", label: "Gurbhakot Municipality" },
    { value: "lekbesi", label: "Lekbesi Municipality" },
    { value: "bheriganga", label: "Bheriganga Municipality" },
    { value: "chaukune", label: "Chaukune Rural Municipality" },
    { value: "duduwa", label: "Duduwa Rural Municipality" },
    { value: "panchapuri", label: "Panchapuri Municipality" },
    { value: "simta", label: "Simta Rural Municipality" }
  ],
  bajura: [
    { value: "badimalika", label: "Badimalika Municipality" },
    { value: "budhiganga", label: "Budhiganga Municipality" },
    { value: "budhinanda", label: "Budhinanda Municipality" },
    { value: "gaumul", label: "Gaumul Rural Municipality" },
    { value: "himali", label: "Himali Rural Municipality" },
    { value: "jagannath", label: "Jagannath Rural Municipality" }
  ],
  bajhang: [
    { value: "jaya_prithvi", label: "Jaya Prithvi Municipality" },
    { value: "bithadchir", label: "Bithadchir Rural Municipality" },
    { value: "chhabis_pathibhera", label: "Chhabis Pathibhera Rural Municipality" },
    { value: "durgathali", label: "Durgathali Rural Municipality" },
    { value: "khaptadchhanna", label: "Khaptadchhanna Rural Municipality" },
    { value: "masta", label: "Masta Rural Municipality" },
    { value: "surma", label: "Surma Rural Municipality" },
    { value: "talkot", label: "Talkot Rural Municipality" },
    { value: "thalara", label: "Thalara Rural Municipality" }
  ],
  darchula: [
    { value: "mahaakali", label: "Mahakali Municipality" },
    { value: "malikarjun", label: "Malikarjun Rural Municipality" },
    { value: "lekam", label: "Lekam Rural Municipality" },
    { value: "naugad", label: "Naugad Rural Municipality" },
    { value: "byas", label: "Byas Rural Municipality" },
    { value: "apihimal", label: "Api Himal Rural Municipality" }
  ],
  baitadi: [
    { value: "dasharathchand", label: "Dasharathchand Municipality" },
    { value: "patan", label: "Patan Municipality" },
    { value: "dilasaini", label: "Dilasaini Rural Municipality" },
    { value: "dogadakedar", label: "Dogadakedar Rural Municipality" },
    { value: "pancheshwor", label: "Pancheshwor Rural Municipality" },
    { value: "purchaudi", label: "Purchaudi Municipality" },
    { value: "shivanath", label: "Shivanath Rural Municipality" },
    { value: "sigas", label: "Sigas Rural Municipality" }
  ],
  dadeldhura: [
    { value: "amargadhi", label: "Amargadhi Municipality" },
    { value: "alital", label: "Alital Rural Municipality" },
    { value: "bhageshwar", label: "Bhageshwar Rural Municipality" },
    { value: "ganeshpur", label: "Ganeshpur Rural Municipality" },
    { value: "nawadurga", label: "Nawadurga Rural Municipality" },
    { value: "parashuram", label: "Parashuram Municipality" }
  ],
  kanchanpur: [
    { value: "bhimdatta", label: "Bhimdatta Municipality" },
    { value: "bedkot", label: "Bedkot Municipality" },
    { value: "belauri", label: "Belauri Municipality" },
    { value: "punarbas", label: "Punarbas Municipality" },
    { value: "shuklaphanta", label: "Shuklaphanta Municipality" },
    { value: "krishnapur", label: "Krishnapur Rural Municipality" },
    { value: "laljhadi", label: "Laljhadi Rural Municipality" }
  ],
  kailali: [
    { value: "dhangadhi", label: "Dhangadhi Sub-Metropolitan City" },
    { value: "ghodaghodi", label: "Ghodaghodi Municipality" },
    { value: "lamkichuha", label: "Lamkichuha Municipality" },
    { value: "tikapur", label: "Tikapur Municipality" },
    { value: "bhajani", label: "Bhajani Municipality" },
    { value: "janaki", label: "Janaki Rural Municipality" },
    { value: "joshipur", label: "Joshipur Rural Municipality" },
    { value: "kailari", label: "Kailari Rural Municipality" },
    { value: "mohanpur", label: "Mohanpur Rural Municipality" }
  ],
  doti: [
    { value: "dipayal_silgadhi", label: "Dipayal Silgadhi Municipality" },
    { value: "adarsa", label: "Adarsha Rural Municipality" },
    { value: "badikedar", label: "Badikedar Rural Municipality" },
    { value: "bogatan_phudsil", label: "Bogatan Phudsil Rural Municipality" },
    { value: "jorayal", label: "Jorayal Rural Municipality" },
    { value: "kathar", label: "Katar Rural Municipality" },
    { value: "purbi_chauki", label: "Purbi Chauki Rural Municipality" },
    { value: "sayal", label: "Sayal Rural Municipality" }
  ],
  achham: [
    { value: "mangalsen", label: "Mangalsen Municipality" },
    { value: "sanphebagar", label: "Sanphebagar Municipality" },
    { value: "bannigadhi_jayagadh", label: "Bannigadhi Jayagadh Rural Municipality" },
    { value: "chaurpati", label: "Chaurpati Rural Municipality" },
    { value: "dhakari", label: "Dhakari Rural Municipality" },
    { value: "kamalbazaar", label: "Kamalbazar Municipality" },
    { value: "mellekh", label: "Mellekh Rural Municipality" },
    { value: "rishikesh", label: "Rishikesh Rural Municipality" },
    { value: "safebagar", label: "Safebagar Rural Municipality" }
  ],
};

export const getStateOptions = (country: string) => {
  return statesByCountry[country] || [];
};

export const getDistrictOptions = (province: string) => {
  return districtsByProvince[province] || [];
};

export const getLocalJurisdictionOptions = (district: string) => {
  return localJurisdictionsByDistrict[district] || [];
};
